version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: deploy-scripts/install_apache.sh
      runas: root
    - location: deploy-scripts/start_apache.sh
      runas: root
   AfterInstall:
    - location: deploy-scripts/restar_tapache.sh
      runas: root